### ISSUE TITLE
provenance replay from q2view

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2view-old#123]
**Addition Description**
During focus group testing of provenance replay, participants requested provenance replay be included in q2view. 

**Current Behavior**
Users have GUI access to the provenance graph, but no easy search access to captured provenance data, and no way of viewing e.g. the interface-specific command associated with an action. See #122.

**Proposed Behavior**
Users could click a button on the provenance graph page to generate and download a script or reproducibility package representing the analysis. Alternately, replay scripts could be generated by default, and this functionality could be included in a separate tab (e.g. with a selector for target interface and a download button.

**Comments**
Many challenges exist here:
- According to @ebolyen, this would probably require a rewrite/fork of provenance replay in Rust, which could be compiled to WASM.
- usage drivers for this platform would likely need to be decoupled from QIIME 2 entirely, and tooling to support version-specific plugin, action, and parameter-name checking doesn't exist outside of the Plugin Manager. Successful replay would require either this kind of tooling, or a relatively comprehensive solution for managing computing environments during replay (e.g. https://github.com/ChrisKeefe/provenance_py/issues/78), so that no name checking was required.
- q2view currently supports the viewing of single artifacts only. In order to get full value out of provenance replay, support for visualizing trees representing multiple artifacts would probably be required.

**Comment by ChrisKeefe** [comment]
Note: q2view currently supports the viewing of single artifacts only. In order to get full value out of provenance replay, support for visualizing trees representing multiple artifacts would probably be required.

**Comment by ebolyen** [comment]
It's possible Python will run well enough in WASM to do this someday.

**Comment by ebolyen** [comment]
Until then, this seems out of scope.
