### ISSUE TITLE
Dropbox shared link not working

### ISSUE THREAD

**Issue by mkariush** [qiime2/q2view-old#127]
Hi, anybody noticed a problem using Dropbox link in https://view.qiime2.org/? Suddenly links stoped working. I realised Dropbox is moving to a new link architecture and I think it must have something to do with it as the shared link generated previously (like a mont ago still work perfectly).

**Comment by ebolyen** [comment]
Hey @mkariush,

I just tested and it seems like it is working. Are you still having issues with this? It's possible there was a brief interruption in the public-link service which stopped it from working.

(Or do you have a browser extension such as noscript installed? I've been bitten by that before.)

**Comment by mkariush** [comment]
Hi Evan,
I have this issue - Network error, recieved 503 from server. If I upload the qzv from my local file system it works. If I move the file to my Dropbox, create a shared link and use this link in the Qiime2 view - it fails with the up mentioned error. The error pops up on two different browsers in Ubuntu and Windows. What I noticed is that the shared link that fail have different format from those that work. Links that do not work  have the following format 
https:// www.dropbox. com/ scl/fi /er5asug7yr8885eauuqly /****.qzv?rlkey=5738ifh0ysp8j9tf00h5rkotp&dl=0
Link that do work have the format 
https://www.dropbox. com/s /4eq6qj6yy58lm3p /***.qzv?dl=0
So I presume it is more a Dropbox related issue but still I have no idea how to fix it. However, if I use the new format link directly in a browser, I have an access to a qzv file and I can download it.

**Comment by ebolyen** [comment]
Thanks for the details @mkariush!

I bet we're losing the query param `rlkey` at some point, since we manipulate those for `dl=0`. I'll see if I can generate a link that looks more like yours to debug this.

**Comment by lizgehret** [comment]
More context on this Dropbox link structure update can be found [here](https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/td-p/689070). We've had another report of this from a forum user, and I was able to recreate this on my end as well @mkariush.

We'll investigate this further and see what we can do to get this resolved - thanks for submitting an issue for it! We'll keep you posted with updates as we have them, thanks for your patience here!
