### ISSUE TITLE
review full issue tracker to plan next steps for QIIME 2 View

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2view-old#129]
After the build is fixed (#128), we should review all issues on this issue tracker to develop a roadmap for this project, including prioritization of issues and remove of issues that are no longer relevant or are not directions that we want to go. I did a full review of the issue tracker in Sept 2023, and many of these still seem like high priority improvements and fixes.

**Comment by ebolyen** [comment]
Done!
