### ISSUE TITLE
add citation styles to q2view details page

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2view-old#137]
It would be convenient for citations to be formattable in different styles before download.  We had a previous PR (#101) that can be used as a reference for this one. (That PR is closed b/c the code itself would need to be reworked for the ongoing q2view updates.)

**Comment by Oddant1** [comment]
@gregcaporaso this ought to be at least mostly working in the rewrite adapted from @David-Rod's code

**Comment by Oddant1** [comment]
Closed in [qiime2/q2view](https://github.com/qiime2/q2view)
