### ISSUE TITLE
q2-view struggles with collection provenance.

### ISSUE THREAD

**Issue by cherman2** [qiime2/q2view-old#138]
**Bug Description**
q2-view can not visualize collection inputs currently. Note that the data is in the artifact if you unzip and look at provenance. q2-view just can not parse it. 

**Steps to reproduce the behavior**
1. Run feature-table tabulate-seqs with a taxonomy as input
2. Look at provenance 

**Expected behavior**
I want to see provenance of my taxonomy 

**Screenshots**
![Screenshot 2024-01-04 at 2 21 57 PM](https://github.com/qiime2/q2view/assets/60228108/2ae028a8-2d83-417e-ae86-ea67a60b6691)

**Comment by cherman2** [comment]
@Oddant1, I think Greg said you were gonna take a look at this.  Feel free to unassign if that isn't the case!

**Comment by Oddant1** [comment]
This should be more or less resolved in the rewrite, but I'm going to leave this open for now

**Comment by ebolyen** [comment]
Basically resolved.
