### ISSUE TITLE
QIIME 2 View refactor should support original URLs

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2view-old#139]
There are a lot of URLs floating around out there that look like the following:
https://view.qiime2.org/provenance/?src=https%3A%2F%2Fdocs.qiime2.org%2F2021.4%2Fdata%2Ftutorials%2Fmoving-pictures%2Fcore-metrics-results%2Funweighted_unifrac_emperor.qzv

The refactored QIIME 2 View site should support the original API, so these links don't break but rather just open with the new QIIME 2 View. 

@Oddant1, do you think that will be a problem?

**Comment by Oddant1** [comment]
@gregcaporaso that ought to already work.

**Comment by gregcaporaso** [comment]
Perfect, thanks @Oddant1! Just wanted to make sure. Feel free to close if you don't need this as a reminder.

**Comment by Oddant1** [comment]
Closed in [qiime2/q2view](https://github.com/qiime2/q2view)
