### ISSUE TITLE
Prevent Redux DevTools from being packed for production

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2view-old#34]
https://view.qiime2.org currently has Redux DevTools enabled. Not a big deal as there is no server talk happening to do anything dangerous whatsoever to the state, but could be a performance blocker.

**Comment by ebolyen** [comment]
I actually left this in on purpose so that we could diagnose issues with the live site. I'd be interested to know if there is a performance difference as the way it is invoked now:
```javascript
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(rootReducer,
                          window.__DEHYDRATED_STORE__,
                          composeEnhancers(makeMiddleware(browserHistory)));
```

looks as if it will results in a noop if the extension isn't installed. I don't think this used to be the case, but it seems pretty efficient nowadays.

**Comment by jakereps** [comment]
Ah ok, yeah might not be a big deal for this case. This could probably be closed then, I was just going off his disclaimer I remembered seeing during the studio build, at https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#gotchas.

> **Make sure to only apply `DevTools.instrument()` and render `<DevTools>` in development!** In production, this will be terribly slow because actions just accumulate forever...

**Comment by zalmoxisus** [comment]
@jakereps, I guess you were confusing the extension with vanilla Redux DevTools. Allowing the extension in production indeed [has no perf impact if not used](https://github.com/zalmoxisus/redux-devtools-extension/issues/185).

**Comment by jakereps** [comment]
Awesome, thanks for that link @zalmoxisus! I'll just close this out then.
