### ISSUE TITLE
Improved Open/Upload Page UX

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2view-old#38]
The open/upload page is a bit confusing right now, maybe using an [alternative UX](http://ux.stackexchange.com/a/21940) we can make this more clear. Perhaps some kind of toggle element that shows either the URL form OR the upload form.

**Comment by ebolyen** [comment]
:+1:  I had originally planned on making the input an omni-bar which would take a URL or a drag and drop (like Google image search), but it proved to be kind of a pain to implement, so I split them in the interest of time.

[This more recent answer](http://ux.stackexchange.com/a/83408) to the same topic has some good examples as well. I like the first example, with the obvious link which toggles the URL form. It is also probably the better emphasis, most people probably have a local file. Those who can make an actually working link-able artifact can probably figure the rest out.

As I think about this more, however the UI works, we should probably provide exposition explaining what kinds of headers (or services, e.g. dropbox) you need to use to get a working artifact link. Which definitely suggests that the link form is the more advanced feature and shouldn't be the default presentation-wise.

**Comment by ebolyen** [comment]
Should also provide some general getting started text (with some example artifacts/visualizations)

**Comment by ebolyen** [comment]
fixed by #57
