### ISSUE TITLE
Allow view.qiime2.org to open Dropbox files

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2view-old#54]
It would be awesome If artifacts hosted in Dropbox could be linked using view.qiime2.org. Right now, the message you get on screen is:

```
Something went wrong!
TypeError: Failed to fetch
```

Alternatively a different error message would also be useful.

**Comment by ebolyen** [comment]
:+1: :+1: :+1: It is currently possible, but you need a magic URL from dropbox. We want to automatically detect the host and convert to that magic CORS-enabled URL.
