### ISSUE TITLE
Visualizations without any artifact inputs don't show up in provenance

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2view-old#60]
[example of this](https://view.qiime2.org/provenance/?src=https%3A%2F%2Fdocs.qiime2.org%2F2017.6%2Fdata%2Ftutorials%2Fmetadata%2Ftabulated-sample-metadata.qzv)

**Comment by thermokarst** [comment]
Fixed in 7cc92e4bb7b0f592e1bf06fd36edb047759a10a1
