### ISSUE TITLE
Need more space in provenance for commands with multiple inputs

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2view-old#61]
**Improvement Description**
If you have multiple inputs, you don't have enough room for the provenance graph. More default space would be nice. :) Not very important though. 

**Screenshots**
<img width="960" alt="screen shot 2017-06-24 at 3 41 16 pm" src="https://user-images.githubusercontent.com/7920357/27512139-0d8a1392-58f4-11e7-8c6c-e6b72e67ef39.png">

**References**
Ported from qiime2/qiime2#290

**Comment by gregcaporaso** [comment]
Closing in favor of #115.
