### ISSUE TITLE
Switching between provenance visualization, peek and provenance resets elements

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2view-old#74]
**Bug Description**
Switching between the `Visualization`, `Peek` and `Provenance` tabs resets the elements. This is not a problem for the `Peek` tab, but it is for the `Visualization` and for the `Provenance` tabs.

Say I have setup a plot to highlight something I'm interested, but then want to look at the provenance, switching back to the visualization shows me the default plot i.e. without the things I had just made. The same happens with `Provenance` where if I'm trying to debug the origin of an artifact, and I've re-arranged the layout of the provenance graph, switching over to a visualization will reset the graph back to its default layout.

**Comment by Oddant1** [comment]
Closed in [qiime2/q2view](https://github.com/qiime2/q2view)
