### ISSUE TITLE
Remove web alert in q2view asking if you want to leave this site

### ISSUE THREAD

**Issue by JTFouquier** [qiime2/q2view-old#75]
**Current Behavior**
I get this every time I try to close a q2view. It's not a big deal but I was closing a lot of views and it was a tad annoying. :) 

**Screenshots**
<img width="506" alt="screen shot 2017-09-19 at 3 22 22 pm" src="https://user-images.githubusercontent.com/7920357/30616148-8abb1afc-9d4e-11e7-85a6-1019e502000b.png">

**Comment by ebolyen** [comment]
What's ironic is I actually went through some pretty great lengths to make that dialog appear at the correct time. What it prevents is navigating away accidentally resulting in your loaded artifact/visualization unloaded, meaning you get that "expired page" error. It is definitely annoying when you are just trying to close the document, but I don't think there's a way to tell the difference from closing the window and navigating away. 

So I guess the question becomes:
   1. If there are different events I could catch, would it make sense to only show this on navigation, not termination.
   2. Is it better to never see this dialog and instead you [see this](https://view.qiime2.org/peek/?src=024e9eff-3644-4e6d-ab99-3c3fc596d344) if you accidentally hit back too many times (this is distinct from losing the viz state, which is also an issue).

**Comment by thermokarst** [comment]
If option 1 is possible, that sounds pretty great to me, otherwise I would rather see this stay as-is --- losing your interactive viz session is a bummer.

**Comment by JTFouquier** [comment]
I spent a good 20 mins googling how to prevent google pop ups before posting. haha. Sorry Evan. It's probably fine for the reason you mention.

**Comment by ebolyen** [comment]
No worries, I get annoyed by it as well. I'm just not sure which is worse, dealing with this, or having to navigate your file tree to find your artifact again. 

Another option would be client-side configuration (stored in the browser), then advanced users could just disable this.

**Comment by JTFouquier** [comment]
Another option (or maybe just a temporary one) is if you can modify the alert to say "Qiime changes you made may not be saved" or something Qiime related. This way they know it's your alert and not just some random Google popup.

**Comment by ebolyen** [comment]
The alert is supplied by the browser, I can't control what it says (and it says different things depending on browser). Assuming option 1 from above is possible then we could probably create our own modal dialog explaining things more clearly.

**Comment by ebolyen** [comment]
Let's set a handler on the logo itself so that it gives you a warning that this navigation will destroy your visualization. We should be able to store a "don't ask me again" flag depending on how this is done.

Then we don't need this more general navigation API which we can't control.

**Comment by Oddant1** [comment]
Closed in [qiime2/q2view](https://github.com/qiime2/q2view)
