### ISSUE TITLE
Incomplete `manifest` object in provenance

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2view-old#76]
Loaded up some [test data](https://github.com/qiime2/q2-quality-filter/blob/master/q2_quality_filter/test/data/real_data.qza) from `q2-quality-filter`, peeked at the provenance:

<img width="474" alt="screen shot 2017-09-28 at 7 41 09 am" src="https://user-images.githubusercontent.com/274668/30972830-869ff9fa-a420-11e7-97bf-8a3ad10fccb2.png">

Cracked open the QZA, peeked at the provenance:

<img width="415" alt="screen shot 2017-09-28 at 7 40 14 am" src="https://user-images.githubusercontent.com/274668/30972861-96a689d6-a420-11e7-8050-36e90aa110b8.png">

The q2view rendering of the provenance is missing the entry for`Undetermined_S0_L001_R1_001.fastq.gz`

**Comment by ebolyen** [comment]
Huh. That's very strange.

**Comment by thermokarst** [comment]
Just noticed the md5sums are different here - I must've goofed when looking at this. New screenshots:

<img width="483" alt="screen shot 2017-09-28 at 2 37 30 pm" src="https://user-images.githubusercontent.com/274668/30991616-996c3104-a45a-11e7-84f4-547c430b73ff.png">

<img width="391" alt="screen shot 2017-09-28 at 2 38 04 pm" src="https://user-images.githubusercontent.com/274668/30991638-b551bf92-a45a-11e7-9c7a-3cf144b36eb3.png">

Don't mind me - keep on QIIME'n!
