### ISSUE TITLE
make gallery dynamic

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2view-old#79]
**Current Behavior**
Right now updating the gallery requires the entire app to be recompiled which is a little silly. 

**References**
There are some [data links](https://github.com/qiime2/data.qiime2.org/blob/7094b17dbe5029745d2087b80c8fbbdf64510557/urls.py#L105-L110) which look like the files we'd ideally use, but data.qiime2.org doesn't set the right kind of headers, so q2view can't actually follow the redirect.

**Comment by ebolyen** [comment]
Better approach, handle this like jupyter-book does:

https://executablebooks.org/en/latest/gallery.html

**Comment by Oddant1** [comment]
Closed in [qiime2/q2view](https://github.com/qiime2/q2view) and [qiime2/q2view-gallery](https://github.com/qiime2/q2view-gallery)
