### ISSUE TITLE
gallery needs more examples!

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2view-old#92]
q2-longitudinal volatility should be on there. Alpha rarefaction too.

**Comment by thermokarst** [comment]
This might be a good task for @ChrisKeefe or @turanoo.

**Comment by thermokarst** [comment]
How about as a second row?

|   |   |   |
| ------------- | ------------- | ------------- |
| taxa barplots  | sampling depth | emperor |
| volatility  | alpha rarefaction | [metadata tabulate?] |

**Comment by nbokulich** [comment]
+1 second row of examples (or more!)

How about:

|   |   |   |
| ------------- | ------------- | ------------- |
| taxa barplots  | volatility | emperor |
| sampling depth | alpha rarefaction | alpha group significance |

no offense to sampling depth, but volatility is just so much more beautiful.

demux summarize could also be a good one.

**Comment by thermokarst** [comment]
On 07/06, Nicholas Bokulich wrote:
> +1 second row of examples (or more!)
> 
> How about:
> 
> |   |   |   |
> | ------------- | ------------- | ------------- |
> | taxa barplots  | volatility | emperor |
> | sampling depth | alpha rarefaction | alpha group significance |

This order sounds good to me!

> 
> no offense to sampling depth, but volatility is just so much more beautiful.

lol

> 
> demux summarize could also be a good one.

:+1:

**Comment by turanoo** [comment]
This looks like a fun task to work on. I'm interested 👀
